x-veld:
  code:
    about:
      description: "A NER trainig setup, utilizing spaCy 3's config system."
      topics:
        - "NLP"
        - "Machine learning"
        - "Named entity recognition"

    inputs:
      volume: /veld/input/
      file_formats: "spacy docbin"

    outputs:
      volume: /veld/output/
      file_formats: 
        - "spacy model"
        - "txt"
      contents:
        - "NLP model"
        - "log file"

    environment:
      in_train_docbin_file:
        type: file
        volume: /veld/input/
      in_dev_docbin_file:
        type: file
        volume: /veld/input/
      in_eval_docbin_file:
        type: file
        volume: /veld/input/
      out_model_folder:
        description: "path to the spacy model"
        type: folder
        volume: /veld/output/
      out_train_log_file:
        description: "path to the train log file"
        type: file
        volume: /veld/output/
      out_eval_log_file:
        description: "path to the eval log file"
        type: file
        volume: /veld/output/

services:
  veld_train:
    build: .
    working_dir: /veld/code/
    command: bash /veld/code/train.sh
    volumes:
      - ./src/train/:/veld/code/
      - ./data/docbin/:/veld/input/
      - ./data/model/:/veld/output/
    environment:
      in_train_docbin_file: null
      in_dev_docbin_file: null
      in_eval_docbin_file: null
      out_model_file: null
      out_train_log_file: null
      out_eval_log_file: null

