x-veld:
  code:
    about:
      description: "A NER trainig setup, utilizing spaCy3's config system."
      topic:
        - "NLP"
        - "Machine learning"
        - "Named entity recognition"
    input:
      -
        type: "file"
        format: "spaCy DocBin"
        content: "Named entity recognition gold data" 
        path: /veld/input/train.spacy
        description: "train data"
      -
        type: "file"
        format: "spaCy DocBin"
        content: "Named entity recognition gold data" 
        path: /veld/input/dev.spacy
        description: "dev data"
      -
        type: "file"
        format: "spaCy DocBin"
        content: "Named entity recognition gold data" 
        path: /veld/input/eval.spacy
        description: "eval data"
    output:
      -
        type: "folder"
        format: "spaCy model"
        content: "NLP model"
        path: /veld/output/model/
      -
        type: "file"
        format: "txt"
        content: "log"
        path: /veld/output/train.log
      -
        type: "file"
        format: "txt"
        content: "log"
        path: /veld/output/eval.log

services:
  veld:
    build: .
    volumes:
      - ./src/:/veld/code/
    command: bash /veld/code/train.sh
