x-veld:
  code:
    # TODO: Shouldn't there be a spacy training config as input somehwere?
    about:
      description: "A NER trainig setup, utilizing spaCy3's config system."
      topics:
        - "NLP"
        - "Machine learning"
        - "Named entity recognition"
    inputs:
      -
        file_formats: "spacy docbin"
        contents: "NER gold data" 
        path: /veld/input/train.spacy
        description: "train data"
      -
        file_formats: "spacy docbin"
        contents: "NER gold data" 
        path: /veld/input/dev.spacy
        description: "dev data"
      -
        file_formats: "spacy docbin"
        contents: "NER gold data" 
        path: /veld/input/eval.spacy
        description: "eval data"
    outputs:
      -
        file_formats: "spacy model"
        contents:
          - "NLP model"
          - "NER model"
        path: /veld/output/model/
      -
        file_formats: "txt"
        contents: "logging"
        path: /veld/output/train.log
      -
        file_formats: "txt"
        contents: "logging"
        path: /veld/output/eval.log

services:
  veld:
    build: .
    command: bash /veld/code/train.sh
    volumes:
      - ./src/:/veld/code/
